name: 'Check updates'
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Touch
        run: |
          touch README.md

      - name: Commit and push changes
        run: |
          git add -A
          git commit -m "updated"
          git push
